server:
  port: 8088
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token # 告诉执行器，连接调度中心的时候，也要写入相同的token
    executor:
      appname: xxl-job-executor-sample # 执行器名称
      address: ""
      ip: 127.0.0.1
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
